name: tna
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - graph-tool
  - pip
  - pip:
    - pandas
    - numpy
    - ipykernel
    - pyarrow
    - jupyter
    - jupyter-cache
    - matplotlib
    - seaborn
